brew cask install google-chrome
brew cask install dropbox
brew cask install google-drive
brew cask install java
brew cask install the-unarchiver
brew cask install whatsapp
brew cask install vlc
brew cask install appcleaner
brew cask install slack
brew cask install visual-studio-code
brew cask install zoomus